from core.database import Base
from sqlalchemy import Boolean, Column, DateTime, Float, Integer, String


class Cases(Base):
    __tablename__ = "cases"
    __table_args__ = {"extend_existing": True}

    id = Column(Integer, primary_key=True, index=True, autoincrement=True, nullable=False)
    user_id = Column(String, nullable=False)
    case_number = Column(String, nullable=True)
    case_status = Column(String, nullable=True)
    case_type = Column(String, nullable=True)
    case_date = Column(String, nullable=True)
    order_date = Column(String, nullable=True)
    fitting_date = Column(String, nullable=True)
    completion_date = Column(String, nullable=True)
    delivery_date = Column(String, nullable=True)
    patient_name = Column(String, nullable=True)
    patient_age = Column(Integer, nullable=True)
    patient_dob = Column(String, nullable=True)
    gender = Column(String, nullable=True)
    patient_address = Column(String, nullable=True)
    living_situation = Column(String, nullable=True)
    facility_name = Column(String, nullable=True)
    discharge_estimate = Column(String, nullable=True)
    insurance_type_id = Column(String, nullable=True)
    insurance_name = Column(String, nullable=True)
    category_id = Column(String, nullable=True)
    category_name = Column(String, nullable=True)
    product_id = Column(String, nullable=True)
    product_name = Column(String, nullable=True)
    side = Column(String, nullable=True)
    disease_name = Column(String, nullable=True)
    disability_name = Column(String, nullable=True)
    disability_site = Column(String, nullable=True)
    disability_detail = Column(String, nullable=True)
    symptoms = Column(String, nullable=True)
    diagnosis = Column(String, nullable=True)
    height_cm = Column(Float, nullable=True)
    weight_kg = Column(Float, nullable=True)
    usage_location = Column(String, nullable=True)
    usage_hours_per_day = Column(Float, nullable=True)
    usage_days_per_week = Column(Float, nullable=True)
    device_name = Column(String, nullable=True)
    expected_effect = Column(String, nullable=True)
    parts_used = Column(String, nullable=True)
    parts_reason_daily = Column(String, nullable=True)
    parts_reason_work = Column(String, nullable=True)
    parts_reason_other = Column(String, nullable=True)
    doctor_name = Column(String, nullable=True)
    hospital_name = Column(String, nullable=True)
    department_name = Column(String, nullable=True)
    bank_transfer = Column(Boolean, nullable=True)
    invoice_needed = Column(Boolean, nullable=True)
    certificate_received = Column(Boolean, nullable=True)
    remarks = Column(String, nullable=True)
    media_files = Column(String, nullable=True)
    created_at = Column(DateTime(timezone=True), nullable=True)
    updated_at = Column(DateTime(timezone=True), nullable=True)